---

- name: install docker
  hosts: all
  become: yes
  roles:
    - docker-install

- name: install node on the server front and back
  hosts: front-back
  become: yes
  roles:
    - node-install

- name: clone front repo from git
  hosts: front
  become: yes
  roles:
    - front-repo

- name: clone back repo from git
  hosts: back
  become: yes
  roles:
    - back-repo
